parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_VERSION): ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # existing migrations will fail if the schema filter is activated
                #schema_filter: ~^(?!(bundle_migration_|kimai2_sessions))~
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                # this setting prevents automatic database detection and finds a lot of false-negatives on doctrine:migrations:diff
                # for null columns with MariaDB. Each migration tries to convert EVERY nullable column.
                server_version: '%env(string:DATABASE_VERSION)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

        types:
            datetime: App\Doctrine\UTCDateTimeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Kimai
                dql:
                    datetime_functions:
                        date: App\Doctrine\Extensions\Date
                        day: App\Doctrine\Extensions\Day
                        month: App\Doctrine\Extensions\Month
                        year: App\Doctrine\Extensions\Year

when@test:
    doctrine:
        dbal:
            logging: false

when@prod:
    doctrine:
        orm:
            metadata_cache_driver:
                type: service
                id: doctrine.system_cache_provider
            query_cache_driver:
                type: service
                id: doctrine.system_cache_provider
            result_cache_driver:
                type: service
                id: doctrine.result_cache_provider

    services:
        doctrine.result_cache_provider:
            factory: [ 'Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap' ]
            class: Doctrine\Common\Cache\Psr6\DoctrineProvider
            public: false
            arguments:
                - '@doctrine.result_cache_pool'
        doctrine.system_cache_provider:
            factory: [ 'Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap' ]
            class: Doctrine\Common\Cache\Psr6\DoctrineProvider
            public: false
            arguments:
                - '@doctrine.system_cache_pool'

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
