# TODO upgrade to 2.8
# https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/2.8.0
fos_rest:
    param_fetcher_listener:
        enabled: true
    cache_dir: '%kernel.cache_dir%/fos_rest'
    routing_loader: false
    body_converter:
        enabled: true
    serializer:
        serialize_null: true
    view:
        formats:
            json: true
            xml: false
        view_response_listener:
            enabled: true
        failed_validation: 400
    exception:
        enabled: true
        map_exception_codes: true
        # --------------------------
        serialize_exceptions: false
        # https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2200#issuecomment-629150462
        # https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2224
        #exception_controller: 'fos_rest.exception.controller:showAction'
        # TODO deprecated with 2.8
        # --------------------------
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 400
            'App\Validator\ValidationFailedException': 400
            'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException': 401
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': 400
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException': true
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
    body_listener:
        enabled: true
        decoders:
            json: fos_rest.decoder.json
        array_normalizer:
            service: fos_rest.normalizer.camel_keys
            forms: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    zone:
        - { path: ^/api/* }

handcraftedinthealps_rest_routing:
    routing_loader:
        default_format: 'json'
        prefix_methods: true
        include_format: true
        formats:
            json: true
            xml: false
