version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
  phan:
    enabled: true
    config:
      file_extensions: "php"
ratings:
  paths:
  - "**.php"
exclude_patterns:
  - ".github/"
  - "assets/"
  - "bin/"
  - "config/"
  - "node_modules/"
  - "public/"
  - "templates/"
  - "tests/"
  - "translations/"
  - "var/"
  - "vendor/"
  - ".*"
