build:
    environment:
        node: v8.11.2
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - js-scrutinizer-run
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --exclude-group integration --coverage-clover=unit tests/'
                coverage:
                    file: 'unit'
                    format: 'clover'
            -
                command: 'vendor/bin/phpunit --group integration --coverage-clover=integration tests/'
                coverage:
                    file: 'integration'
                    format: 'clover'
#            -
#                command: 'bin/console kimai:phpcs --checkstyle=checkstyle'
#                analysis:
#                    file: 'checkstyle'
#                    format: 'general-checkstyle'

filter:
    excluded_paths:
        - '.github/*'
        - 'bin/*'
        - 'config/*'
        - 'node_modules/*'
        - 'public/*'
        - 'templates/*'
        - 'translations/*'
        - 'var/*'
        - 'vendor/*'

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - '.github/*'
                - 'assets/*'
                - 'bin/*'
                - 'config/*'
                - 'node_modules/*'
                - 'public/*'
                - 'templates/*'
                - 'translations/*'
                - 'var/*'
                - 'vendor/*'
    php_cs_fixer:
        enabled: true
#        config:
#            level: psr2
        filter:
            excluded_paths:
                - '.github/*'
                - 'assets/*'
                - 'bin/*'
                - 'config/*'
                - 'node_modules/*'
                - 'public/*'
                - 'templates/*'
                - 'translations/*'
                - 'var/*'
                - 'vendor/*'
checks:
    php: true
    javascript: true
