build:
    environment:
        node: v8.11.2
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run
        tests: true
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --testsuite unit --coverage-clover=unit'
                coverage:
                    file: 'unit'
                    format: 'clover'
            -
                command: 'vendor/bin/phpunit --testsuite integration --coverage-clover=integration'
                coverage:
                    file: 'integration'
                    format: 'clover'

filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - '*/build/*'
        - 'node_modules/*'
        - 'public/*'
        - 'var/*'
        - 'vendor/*'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
