dist: trusty
language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

matrix:
  include:
    - stage: Test
      php: '7.2'
      env: CODECOVERAGE=0 DB=mysql
      sudo: required
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client
      before_install:
        - mysql --version
        - sudo mysql_upgrade
        - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo service mysql restart
        - mysql --version
    - stage: Test
      php: '7.3'
      env: CODECOVERAGE=0 DB=mysql
      sudo: required
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client
      before_install:
        - mysql --version
        - sudo mysql_upgrade
        - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo service mysql restart
        - mysql --version
    - stage: Test
      php: '7.2'
      env: CODECOVERAGE=0 DB=sqlite
    - stage: Test
      #php: '7.4snapshot'
      php: '7.3'
      env: CODECOVERAGE=0 DB=sqlite
    - stage: Test
      php: '7.2'
      env: CODECOVERAGE=0 DB=mariadb
      addons:
        mariadb: '10.2'
    - stage: Test
      php: '7.3'
      env: CODECOVERAGE=0 DB=mariadb
      addons:
        mariadb: '10.2'
    - stage: Test
      php: '7.3'
      env: CODECOVERAGE=1 DB=sqlite
      after_success:
        - if [[ $CODECOVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
    - stage: Code quality
      env: CODECOVERAGE=0 DB=sqlite
      php: '7.3'
      script:
        - composer validate --no-check-all --strict
        - composer kimai:codestyle
        - composer kimai:phpstan

before_install:
  #  - phpenv config-rm xdebug.ini
  - composer self-update
  - php -i
  - php -m

install:
  - composer install
  - composer require zendframework/zend-ldap

script:
  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit tests/ --coverage-clover=coverage.xml; fi;
  - if [[ $CODECOVERAGE == 0 ]]; then vendor/bin/phpunit tests/; fi;
  - if [[ $DB == 'sqlite' ]]; then cp tests/.env.dist.sqlite .env; fi;
  - if [[ $DB == "mysql" || $DB == "mariadb" ]]; then cp tests/.env.dist.mysql .env; fi;
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n

