language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  mariadb: '10.2'

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before_install:
#  - phpenv config-rm xdebug.ini
  - composer self-update
  - php -i

install:
  - composer install

script:
  - composer codestyle
  - composer phpstan
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then vendor/bin/phpunit tests/ --coverage-clover=coverage.xml; else vendor/bin/phpunit tests/; fi;
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then bash <(curl -s https://codecov.io/bash); fi;
  - cp tests/.env.dist.sqlite .env
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n
  - cp tests/.env.dist.mysql .env
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n
