App\Entity\User:
    exclusion_policy: All
    custom_accessor_order: [id, alias, title, avatar]
    properties:
        id:
            include: true
            groups: [Default]
        alias:
            include: true
            groups: [Default]
        title:
            include: true
            groups: [Entity]
        avatar:
            include: true
            groups: [Entity]
